import { Property } from "@/app/types";

const properties: Property[] = [
  {
    id: 1,
    title: "Premium Plot in Gachibowli test",
    slug: "premium-plot-in-gachibowli-test",
    location: "Gachibowli",
    city: "Hyderabad",
    state: "Telangana",
    price: 4500000,
    area: 2000,
    type: "DTCP Approved Plot",
    facing: "East",
    roadWidth: 40,
    possession: "Immediate",
    isGated: false,
    amenities: ["Parking", "Water", "Security", "Electricity", "Gym", "Club", "Park", "Road", "Swimming Pool"],
    image: "https://subhagruha.com/uploads/1653215609.jpeg",
    description: "Premium residential plot near IT hub with wide roads and clear title.",
    status: "available",
    featured: true,
    createdAt: "2026-02-01",
  },
  {
    id: 2,
    title: "Open Land for Sale",
    slug: "open-land-for-sale",
    location: "Shamshabad",
    city: "Hyderabad",
    state: "Telangana",
    price: 3000000,
    area: 1800,
    type: "Residential Plot",
    facing: "West",
    roadWidth: 33,
    possession: "3 Months",
    isGated: false,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHNzDvBkcllbSBZ24e4V-ecOCUNs8kZSZclA&s",
    description: "Affordable open land near airport highway with good investment return.",
    amenities: ["Water", "Electricity"],
    status: "available",
    featured: false,
    createdAt: "2026-04-01"
  },
  {
    id: 3,
    title: "Luxury Corner Plot",
    slug: "luxury-corner-plot",
    location: "Miyapur",
    city: "Hyderabad",
    state: "Telangana",
    price: 7500000,
    area: 2500,
    type: "Corner Plot",
    facing: "North-East",
    roadWidth: 60,
    possession: "Immediate",
    isGated: true,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQILhQLPg1JS3DJx1TjCf6W6glX66eP3RT1Yg&s",
    description: "Corner facing premium plot with 40ft road access and park view.",
    amenities: ["Parking", "Water", "Security", "Swimming Pool"],
    status: "sold",
    featured: true,
    createdAt: "2026-01-20"
  },
  {
    id: 4,
    title: "Luxury HMDA Plot in Kompally Gated Community",
    slug: "luxury-hmda-plot-in-kompally-gated-community",
    location: "Near NH-44, Kompally",
    city: "Hyderabad",
    state: "Telangana",
    price: 5200000,
    area: 2200,
    type: "HMDA Approved Plot",
    facing: "East",
    roadWidth: 40,
    possession: "Immediate",
    isGated: true,
    label: "Gated Community",
    image: [
      "https://royalepavani.weebly.com/uploads/1/4/7/6/147651071/hmda-approved-plots-in-hyderabad_orig.jpeg",
      "https://subhagruha.com/uploads/1653215609.jpeg",
      "https://static.360realtors.com/properties/photos/7590/floorplans/1751699090_0floorplansimage.webp"
    ],
    description: "Premium HMDA approved residential plot in a luxury gated community. Features 40ft wide internal roads, underground drainage, and landscaped parks. Located just 5 mins from Kompally junction with 24/7 security and CC camera surveillance.",
    amenities: ["Parking", "Water", "Security", "Electricity", "Gym", "Club", "Park", "Road", "Swimming Pool"],
    status: "available",
    featured: true,
    sellerName: "Srinivas Rao",
    sellerType: "Agent",
    contact: "9123456789",
    createdAt: "2026-03-15"
  },
  {
    id: 5,
    title: "Premium Villa Plot in Kukatpally",
    slug: "premium-villa-plot-in-kukatpally",
    location: "Kukatpally",
    city: "Hyderabad",
    state: "Telangana",
    price: 6800000,
    area: 2400,
    type: "Villa Plot",
    facing: "South",
    roadWidth: 40,
    possession: "6 Months",
    isGated: true,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVyzA6hs5aPKADGCi1qGvKo2-qhw2P9SEtag&s",
    description: "Spacious villa plot located near metro station with excellent road connectivity.",
    amenities: ["Parking", "Water", "Security", "Swimming Pool"],
    status: "available",
    featured: true,
    createdAt: "2026-04-05"
  },
  {
    id: 6,
    title: "Investment Plot in Adibatla",
    slug: "investment-plot-in-adibatla",
    location: "Adibatla",
    city: "Hyderabad",
    state: "Telangana",
    price: 3500000,
    area: 1800,
    type: "Residential Plot",
    facing: "North",
    roadWidth: 30,
    possession: "Immediate",
    isGated: false,
    amenities: ["Water", "Electricity"],
    image: "https://static.360realtors.com/properties/photos/7590/floorplans/1751699090_0floorplansimage.webp",
    description: "Best investment plot near Pharma City with high growth potential and clear title.",

    status: "sold",
    featured: false,
    createdAt: "2026-01-25"
  },
  {
    id: 7,
    title: "Beachside Plot in Candolim",
    slug: "beachside-plot-in-candolim",
    location: "Candolim",
    city: "Goa",
    state: "Goa",
    price: 8500000,
    area: 2000,
    type: "Beachside Plot",
    facing: "West",
    roadWidth: 30,
    possession: "Immediate",
    isGated: false,
    image: "https://images.nobroker.in/images/8aa988d09c135f5b019c13cbd7f23257/8aa988d09c135f5b019c13cbd7f23257_70916_454986_medium.jpg",
    description: "Beautiful beachside plot in North Goa for resort development.",
    amenities: ["Water", "Electricity"],
    status: "available",
    featured: true,
    createdAt: "2026-05-10"
  },
  {
    id: 8,
    title: "Hillview Plot in Ooty",
    slug: "hillview-plot-in-ooty",
    location: "Ooty Central",
    city: "Ooty",
    state: "Tamil Nadu",
    price: 6500000,
    area: 1800,
    type: "Hillview Plot",
    facing: "East",
    roadWidth: 33,
    possession: "3 Months",
    isGated: false,
    image: "https://housing-images.n7net.in/01c16c28/b179d9784c2603774025da0483304a8c/v0/medium/residential_plot-for-sale-guirdolim-Goa-plot_view.jpg",
    description: "Scenic hillview plot perfect for vacation homes.",
    amenities: ["Water", "Parking"],
    status: "available",
    featured: false,
    createdAt: "2026-06-15"
  },
  {
    id: 10,
    title: "Luxury Plot in Andheri East",
    slug: "luxury-plot-in-andheri-east",
    location: "Andheri East",
    city: "Mumbai",
    state: "Maharashtra",
    price: 12000000,
    area: 2500,
    type: "Luxury Plot",
    facing: "East",
    roadWidth: 60,
    possession: "Immediate",
    isGated: true,
    image: "https://thewhitelistedestates.in/wp-content/uploads/2025/10/plots-sale-goa-1.webp",
    description: "Premium plot in bustling Mumbai locality with easy metro access.",
    amenities: ["Parking", "Water", "Security", "Swimming Pool"],
    status: "available",
    featured: true,
    createdAt: "2026-02-18"
  }
];

export default properties;
