import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import Header from "./components/header";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans m-0 antialiased`}>
        {/* Fixed Header */}
        <Header />

        {/* Main content with padding-top to avoid overlap */}
        <main style={{ paddingTop: "80px" }}>
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
